name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Export Marimo notebook to HTML
        run: |
          marimo export html-wasm home.py -o output_dir --mode edit

      - name: Post-processing HTML
        run: |
          python postprocessing.py

      - name: Copy favicon assets
        run: |
          cp -f favicons/favicon.ico output_dir/favicon.ico
          cp -f favicons/favicon-16x16.png output_dir/favicon-16x16.png
          cp -f favicons/favicon-32x32.png output_dir/favicon-32x32.png
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: savannahostrowski/savannah.dev:latest